remove fixed port numbers for HTTP/HTTPS connections

diff --git a/source/Dockerfile b/source/Dockerfile
--- a/source/Dockerfile
+++ b/source/Dockerfile
@@ -19,6 +19,10 @@ COPY ./gpfsConfig/mmsdrfs* /var/mmfs/gen/
 COPY ./gpfsConfig/ZIMon* /opt/IBM/zimon/
 
 
+ARG HTTPPROTOCOL=http
+ENV PROTOCOL=$HTTPPROTOCOL
+RUN echo "the HTTP/S protocol is set to $PROTOCOL"
+
 ARG HTTPPORT=4242
 ENV PORT=$HTTPPORT
 RUN echo "the HTTP/S port is set to $PORT" 
@@ -32,7 +36,7 @@ ENV TLSKEYFILE=$KEYFILE
 ARG CERTFILE=None
 ENV TLSCERTFILE=$CERTFILE
 
-RUN if [ -z "$TLSKEYPATH" ] || [ -z "$TLSCERTFILE" ] || [ -z "$TLSKEYFILE" ] && [ "$PORT" -eq 8443 ]; then echo "TLSKEYPATH FOR SSL CONNECTION NOT SET - ERROR"; exit 1; else echo "PASS"; fi
+RUN if [ -z "$TLSKEYPATH" ] || [ -z "$TLSCERTFILE" ] || [ -z "$TLSKEYFILE" ] && [ "$PROTOCOL" = "https" ]; then echo "TLSKEYPATH FOR SSL CONNECTION NOT SET - ERROR"; exit 1; else echo "PASS"; fi
 RUN echo "the ssl certificates path is set to $TLSKEYPATH" 
 
 ARG PMCOLLECTORIP=0.0.0.0
@@ -42,7 +46,7 @@ RUN echo "the pmcollector server ip is set to $SERVER"
 
 WORKDIR /opt/IBM/bridge
 
-ARG DEFAULTLOGPATH='/var/log/ibm_bridge_for_grafanalogs/install.log'
+ARG DEFAULTLOGPATH='/var/log/ibm_bridge_for_grafana/install.log'
 ENV LOGPATH=$DEFAULTLOGPATH
 RUN mkdir -p $(dirname $LOGPATH)
 RUN echo "the log will use $(dirname $LOGPATH)"
@@ -54,7 +58,7 @@ RUN echo "pmcollector_server: $SERVER" >> $LOGPATH
 RUN echo "ssl certificates location: $TLSKEYPATH" >> $LOGPATH
 RUN echo "HTTP/S port: $PORT" >> $LOGPATH
 
-CMD ["sh", "-c", "python3 zimonGrafanaIntf.py -c 10 -s $SERVER -p $PORT -t $TLSKEYPATH --tlsKeyFile $TLSKEYFILE --tlsCertFile $TLSCERTFILE"]
+CMD ["sh", "-c", "python3 zimonGrafanaIntf.py -c 10 -s $SERVER -r $PROTOCOL -p $PORT -t $TLSKEYPATH --tlsKeyFile $TLSKEYFILE --tlsCertFile $TLSCERTFILE"]
 
 EXPOSE 4242 8443
 
