Add the HTTPS port to a Docker container support

diff --git a/source/Dockerfile b/source/Dockerfile
--- a/source/Dockerfile
+++ b/source/Dockerfile
@@ -19,6 +19,14 @@ COPY ./gpfsConfig/mmsdrfs* /var/mmfs/gen/
 COPY ./gpfsConfig/ZIMon* /opt/IBM/zimon/
 
 
+ARG HTTPPORT=4242
+ENV PORT=$HTTPPORT
+RUN echo "the HTTP/S port is set to $PORT" 
+
+ARG CERTPATH
+ENV KEYPATH=$CERTPATH
+RUN if [ -z "$KEYPATH" ] && [ "$PORT" -eq 8443 ]; then echo "KEYPATH FOR SSL CONNECTION NOT SET - ERROR"; exit 1; else echo "PASS"; fi
+RUN echo "the ssl certificates path is set to $KEYPATH" 
 
 ARG PMCOLLECTORIP=0.0.0.0
 ENV SERVER=$PMCOLLECTORIP
@@ -36,9 +44,11 @@ RUN echo "$(pwd)"
 RUN touch $LOGPATH
 RUN echo "log path: $(dirname $LOGPATH)" >> $LOGPATH
 RUN echo "pmcollector_server: $SERVER" >> $LOGPATH
+RUN echo "ssl certificates location: $KEYPATH" >> $LOGPATH
+RUN echo "HTTP/S port: $PORT" >> $LOGPATH
 
-CMD ["sh", "-c", "python3 zimonGrafanaIntf.py -c 10 -s $SERVER"]
+CMD ["sh", "-c", "python3 zimonGrafanaIntf.py -c 10 -s $SERVER -p $PORT -k $KEYPATH"]
 
-EXPOSE 4242
+EXPOSE 4242 8443
 
 #CMD ["tail", "-f", "/dev/null"]
